plugins {
    id 'java-library'
}

apply from: "${rootDir}/versions.gradle"

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.4.5"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // MapStruct
    implementation "org.mapstruct:mapstruct:${versions.mapstruct}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${versions.mapstruct}"
    // Совместимость MapStruct с Lombok
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${versions.mapstruct_lombok_binding}"
}

test {
    useJUnitPlatform()
}