# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name celestica-shop.com www.celestica-shop.com admin.celestica-shop.com www.admin.celestica-shop.com;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Клиентская часть
server {
    listen 443 ssl;
    server_name celestica-shop.com www.celestica-shop.com;

    ssl_certificate /etc/letsencrypt/live/celestica-shop.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/celestica-shop.com/privkey.pem;

    root /usr/share/nginx/html/client;
    index index.html;

    # API для клиентской части(api указывается в переменной REACT_APP_API_BASE_URL_CLIENT для фронта клиента)
    location /api/ {
        # имя контейнера и порт внутри сети Docker(конечный слэш обязателен!)
        proxy_pass http://client-backend:8083/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri /index.html;
    }
}

# Админка
server {
    listen 443 ssl;
    server_name admin.celestica-shop.com www.admin.celestica-shop.com;

    ssl_certificate /etc/letsencrypt/live/celestica-shop.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/celestica-shop.com/privkey.pem;

    root /usr/share/nginx/html/admin;
    index index.html;

    # API для админки(admin-api указывается в переменной REACT_APP_API_BASE_URL_ADMIN для фронта админки)
    location /admin-api/ {
        # имя контейнера и порт внутри сети Docker(конечный слэш обязателен!)
        proxy_pass http://admin-backend:8084/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri /index.html;
    }
}