server {
    listen 80;
    server_name celestica-shop.com www.celestica-shop.com;
    root /usr/share/nginx/html/client;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
   server_name admin.celestica-shop.com www.admin.celestica-shop.com;
    root /usr/share/nginx/html/admin;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}