server:
  port: 8083

app:
  user:
    registration:
      mail:
        from: sales@celestica-shop.com
        subject: Confirming registration
        body: Hi there! Link for your activation
      activation-url: http://localhost:3001/activation
      activation-token:
        expiration: 86400000
  image:
    products:
      bucket: /home/andrey/packages/online-shop/images/products
      prefix-file-name: "product_"
  debug:
    enable-global-context: true
  cors:
    allowed-origins:
      - http://localhost:3001
      - http://192.168.21.38:3001

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: none
    open-in-view: false
    show-sql: true
  liquibase:
    enabled: false
  mail:
    host: ${MAIL_SERVICE_HOST:mail.gmail.com}
    port: 465
    username: ${MAIL_SERVICE_USERNAME:user@mail.com}
    password: ${MAIL_SERVICE_PASSWORD:123}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    org.springframework: INFO
    com.admiral.onlineshop: DEBUG
    liquibase: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: vHk91JhfSOp2kFDrZmHmbdPXuLiS5KEYyyBHPOcm92rqot0M47pV7cGDJbZMEWg
  expiration: 86400000  # 24 часа в миллисекундах
cookie:
  name: authToken
  expiration: 86400000  # 24 часа в миллисекундах